# Generated by Django 5.1.2 on 2024-10-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='uuid',
            field=models.CharField(default='default-uuid-placeholder', editable=False, max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
