# Generated by Django 5.1.2 on 2024-10-12 18:45

import movie_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_collections_uuid_alter_movie_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collections',
            name='uuid',
            field=models.CharField(default=movie_app.models.generate_uuid, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.CharField(default=movie_app.models.generate_uuid, editable=False, max_length=36, unique=True),
        ),
    ]
